name: Build release

on:
  push:
    tags:
      - freeipa-jpegphoto-*

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:35

    steps:
    - name: Install build tools
      run: dnf install -y git tito

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install build dependencies
      run: dnf builddep -y $GITHUB_WORKSPACE/freeipa-jpegphoto.spec

    - name: Build rpm
      run: |
        cd $GITHUB_WORKSPACE
        tito build --offline --rpm -o .

    - name: Test installation of built rpm
      run: dnf install -y noarch/*.rpm

    - uses: actions/upload-artifact@v2
      with:
        name: rpms
        path: ${{ github.workspace }}/noarch/*.rpm

