name: CI

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - freeipa-jpegphoto-*
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        container: ["fedora:37", "fedora:38", "fedora:39", "rockylinux:9", "rockylinux:9.3"]
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
    - name: Enable EPEL (if rockylinux)
      if: "${{ startsWith(matrix.container, 'rockylinux:') }}"
      run: dnf install -y epel-release

    - name: Install build tools
      run: dnf install -y git tito

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - name: Install build dependencies
      run: dnf builddep -y $GITHUB_WORKSPACE/freeipa-jpegphoto.spec

    - name: Build rpm
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        cd $GITHUB_WORKSPACE
        tito build --test --rpm -o .

    - name: Test installation of built rpm
      run: dnf install -y noarch/*.rpm

    - uses: actions/upload-artifact@v3
      with:
        name: rpms
        path: ${{ github.workspace }}/noarch/*.rpm

